### ISSUE TITLE
SMTP settings are required to send mail

### ISSUE THREAD

**Issue by singpolyma** [n0emis/ansible-role-bigbluebutton#58] opened 2020-07-25 03:10 UTC
"Defaults to sendmail" is not really true, since there is no sendmail inside the docker container for it to use.  So without SMTP settings it just doesn't work.  README should be updated for this.

I also suggest that allow_mail_notifications default to `false` unless SMTP is set up.

**Comment by n0emis** [comment] 2020-12-04 16:31
Duplicate of #38

**Closed by n0emis** 2020-12-04 16:31 UTC
